/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateProjcteArgs } from "./CreateProjcteArgs";
import { UpdateProjcteArgs } from "./UpdateProjcteArgs";
import { DeleteProjcteArgs } from "./DeleteProjcteArgs";
import { ProjcteFindManyArgs } from "./ProjcteFindManyArgs";
import { ProjcteFindUniqueArgs } from "./ProjcteFindUniqueArgs";
import { Projcte } from "./Projcte";
import { TaskFindManyArgs } from "../../task/base/TaskFindManyArgs";
import { Task } from "../../task/base/Task";
import { User } from "../../user/base/User";
import { ProjcteService } from "../projcte.service";

@graphql.Resolver(() => Projcte)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ProjcteResolverBase {
  constructor(
    protected readonly service: ProjcteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Projcte",
    action: "read",
    possession: "any",
  })
  async _projctesMeta(
    @graphql.Args() args: ProjcteFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Projcte])
  @nestAccessControl.UseRoles({
    resource: "Projcte",
    action: "read",
    possession: "any",
  })
  async projctes(
    @graphql.Args() args: ProjcteFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Projcte[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Projcte",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Projcte, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Projcte",
    action: "read",
    possession: "own",
  })
  async projcte(
    @graphql.Args() args: ProjcteFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Projcte | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Projcte",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Projcte)
  @nestAccessControl.UseRoles({
    resource: "Projcte",
    action: "create",
    possession: "any",
  })
  async createProjcte(
    @graphql.Args() args: CreateProjcteArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Projcte> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Projcte",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Projcte"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        owner: {
          connect: args.data.owner,
        },
      },
    });
  }

  @graphql.Mutation(() => Projcte)
  @nestAccessControl.UseRoles({
    resource: "Projcte",
    action: "update",
    possession: "any",
  })
  async updateProjcte(
    @graphql.Args() args: UpdateProjcteArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Projcte | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Projcte",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Projcte"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          owner: {
            connect: args.data.owner,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Projcte)
  @nestAccessControl.UseRoles({
    resource: "Projcte",
    action: "delete",
    possession: "any",
  })
  async deleteProjcte(
    @graphql.Args() args: DeleteProjcteArgs
  ): Promise<Projcte | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Task])
  @nestAccessControl.UseRoles({
    resource: "Projcte",
    action: "read",
    possession: "any",
  })
  async tasks(
    @graphql.Parent() parent: Projcte,
    @graphql.Args() args: TaskFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Task[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Task",
    });
    const results = await this.service.findTasks(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Projcte",
    action: "read",
    possession: "any",
  })
  async owner(
    @graphql.Parent() parent: Projcte,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getOwner(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
